services:
  app:
    build:
      context: .
    image: laravel-test-for-devops:latest
    container_name: laravel-test-for-devops
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    restart: unless-stopped
